// AUTO-GENERATED by scripts/generate-blur.mjs — do not edit by hand.
// Regenerate with `npm run blur` (runs automatically on `prebuild`).

export const BLUR_DATA: Record<string, string> = {
  "/vsl/logo.png": "data:image/webp;base64,UklGRiYBAABXRUJQVlA4WAoAAAAQAAAADgAADwAAQUxQSJ4AAAABgJtt27HnevFbQevKXCFt0hkTWKVtJwM4nY0BssBfpbXZ/vYKETEBRBcmSbyS5iykjKXZ2EMRKaRSBmpfKsi2EDO1sPfOfWtBGuwFVeM3996AJ9CFMtXufwX8/sC/2xOoRCGTMst7lprKTgLruzlE1/QFPAUra4CQSpsZC1wiXIqomqFADYqYmsk3M0LEMTuHIraitQwRhyDNSIIiClZQOCBiAAAA0AEAnQEqDwAQAAOAWiWMAnR/AIJQlQAA4BigeltWOD05aq/kOmrij7x0kaJnu5ACdDcbLlKg3x63SWrP/+NbyL4xYi9r3bQC+tE8azpdgsYRDoCiPe2Fc/Qvt4Q8hCq7QAA=",
  "/vsl/marquee/10ft-studio.png": "data:image/webp;base64,UklGRogAAABXRUJQVlA4WAoAAAAQAAAADwAACAAAQUxQSEUAAAABYBPZtpN7P1D+JOBXJAMMfc5WUIBcekxkUBARZAMUhc0jeCU9T5AkXkqkc+ekliY44WHdtyUvs1KBpwnrwilr7DG/3wAAVlA4IBwAAABQAQCdASoQAAkAD8BaJaQABHQAAP0x//+vgAAA",
  "/vsl/marquee/byeb.png": "data:image/webp;base64,UklGRoIAAABXRUJQVlA4WAoAAAAQAAAADwAACAAAQUxQSEAAAAABYFTbtpL7ZeqCw8graRkiUIGmToOIUNi2DVIY7xF8IzmJH+SVj7NC3rfQx7hu+wh2D61wQ+3wdPN6TUEo/fgIVlA4IBwAAABQAQCdASoQAAkAA4BaJaQABHQAAPhX//sNgAAA",
  "/vsl/marquee/commission-club.png": "data:image/webp;base64,UklGRpIAAABXRUJQVlA4WAoAAAAQAAAADwAACAAAQUxQSDUAAAABYBRJkqJa/q8BhiNh5/rM8CmICLIBisLmEV4pBJ8U+ElKKZU8o9mP3LY2h7tRxlmtAX6/AQBWUDggNgAAADABAJ0BKhAACQADgFolnAADcAD+2J9///6DH//0Jv3syP6jPBz8pnPflAIESAE710JKJQQAAA==",
  "/vsl/marquee/diamond-institute.png": "data:image/webp;base64,UklGRrgAAABXRUJQVlA4WAoAAAAQAAAADwAACAAAQUxQSDMAAAABYBPZtpN73k8lJZTZCAaiNxT/JCEiJkB9MaAqSwkN5zbPrmb8r++ZShJHMherDFA16g8AVlA4IF4AAADwAQCdASoQAAkAA4BaJbACdAYpkzf7wAAA9AuMbiBwAPNOu0j4ANmKmZTf5qjctmr3Utyd/NW+MQ9/915GsV/7Sbb8zTC5ztt/h/3+YAvftFd0MLNk5dGSifMlkHAA",
  "/vsl/script/advisory-conversations.png": "data:image/webp;base64,UklGRiQAAABXRUJQVlA4IBgAAAAwAQCdASoQAAgAA4BaJaQAA3AA/vQRgAA=",
  "/vsl/script/compliance-rate.png": "data:image/webp;base64,UklGRigAAABXRUJQVlA4IBwAAAAwAQCdASoQAAYAA4BaJaQAA3AA/vPhLphRQAAA",
  "/vsl/script/referral-funnel.png": "data:image/webp;base64,UklGRiwAAABXRUJQVlA4ICAAAAAwAQCdASoQAAUAA4BaJZwAA3AA/vN+79+2MjIHjgAAAA==",
  "/vsl/testimonials/cc-1.jpeg": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAADQAQCdASoQAAkAA4BaJQBOj+ADA0TyAAD+8YTqVVsWh0vJSPMdHOAYWGeTLLPKd7K5IVJUDNzscqr47fKAsGCE/XEYFAAA",
  "/vsl/testimonials/cc-2.jpeg": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAADQAQCdASoQAAkAA4BaJQBOj+ADA0TyAAD+8YTqVVsWh0vJSPMdHOAYWGeTLLPKd7K5IVJUDNzscqr47fKAsGCE/XEYFAAA",
  "/vsl/testimonials/cc-logo.png": "data:image/webp;base64,UklGRsQAAABXRUJQVlA4WAoAAAAQAAAADwAABwAAQUxQSGoAAAANcBvbtqrs7//jrpE7HTEUQR3UQxWkZO4OkbtDCRExAfxXLBemlZlweydeUyX89ap0AQTgplxugnoUgNsNbjQahcmRC4ArMNLYFGthuyuyVhZLzZxD2okn26k7TXp7jXF7ub9yEJawXYwAVlA4IDQAAABQAQCdASoQAAgAA4BaJZQABDOAAP70SI4HOySA2jFryeG7319ULEhhUiH1NLx0WWpCUAAA",
  "/vsl/testimonials/diamond-1.png": "data:image/webp;base64,UklGRiwAAABXRUJQVlA4ICAAAAAwAQCdASoQAAoAA4BaJaQAA3AA/vQEGg8daWOqBAAAAA==",
  "/vsl/testimonials/diamond-2.jpeg": "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAAAQAgCdASoQAAsAA4BaJYgCdAEVLIq9j9gAAP7xhkNRMcDLplFIvGHl8lrKelxQX1va808ROsVZijKwBECvGRecDWJz0K1WcqWCDV4PkvmJmowL6Qng1Q9C+haBzO9DBAAAAA==",
  "/vsl/testimonials/diamond-3.jpeg": "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAADwAQCdASoQAAsAA4BaJZACdAEPCwGJIAAA/vRZJAoeFvwhdc0UgpATaPgW9Vkoa/pEW+QkRoOidREVm3G0fO3T67XBPUYjeY3QZbZr44sq99iAWHdlkNUaO7QL7/lAAAA=",
  "/vsl/testimonials/diamond-logo.png": "data:image/webp;base64,UklGRgoBAABXRUJQVlA4WAoAAAAQAAAADwAABwAAQUxQSG8AAAABcBvbtqqc897/H3d3GiB0d3epw2mFWFNCKqAHQpr50ENETAAESIL4T5NqgtQ0VVOFbv+8PLrVcbXbmyZB4PD5vmvLzWm7OXqg37xqaKzL3U4hXQqDiHQgPX6zzW3y+CwgZucUBEgQP6WQIEGCBAAAVlA4IHQAAADQAQCdASoQAAgAA4BaJbACdAYq+1uL4ADN6ctyrsm11S3EPz6n+Th/ecD84+VZpoEh7a9mzxnPiZ6GULWC3Jy8LDhFvJzqbv6WEunkPsU2sM5J0O6BkoHWZn+4nMqML8HccSiSejRk5QnBhnwIF5fGUAAAAA==",
  "/vsl/testimonials/galriv-1.png": "data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAABwAQCdASoQAAkAA4BaJZ12AAGIAAD+8E+ng1tnkMXPJw4GBYnS0e+klt3MnYadGfucgDhNvQAAAA==",
  "/vsl/testimonials/galriv-2.png": "data:image/webp;base64,UklGRjYAAABXRUJQVlA4ICoAAACwAQCdASoQAAUAA4BaJZwAAvc1IXHgAP7tZG2HaFSqTEp4N5D+M8i4AAA=",
  "/vsl/testimonials/galriv-logo.png": "data:image/webp;base64,UklGRn4AAABXRUJQVlA4WAoAAAAQAAAADwAAAwAAQUxQSC0AAAABYBvZVqpLBUQQErrzXWPvvyRaiIgEQes62Kmnmdm4LlkAofK/kxPVZ1WHQhsAVlA4ICoAAABwAQCdASoQAAQAA4BaJaACdAFAAAD+0DfAegDPGCgR6+5G7/9qrJjAgAA=",
};
