// AUTO-GENERATED by scripts/generate-blur.mjs — do not edit by hand.
// Regenerate with `npm run blur` (runs automatically on `prebuild`).

export const BLUR_DATA: Record<string, string> = {
  "/vsl/logo.png": "data:image/webp;base64,UklGRi4BAABXRUJQVlA4WAoAAAAQAAAADgAADwAAQUxQSJ8AAAABgJtt27HnfvGbA7jz/0cz2NYETlrb7tK5tLVCSrdOm5T+/H0rRMQEQNPKoJeiLQxKtExY2QKBklDGGSofi+CzQ514k/0P11dWwOSN1E2cvgnCr9AFZqk8+BCEf+Hz7ksoBSNWWzC3c6YpZ0fYXItCnaNb+IsvLQMglHELRoRLwM2gyjEg1INBk2Ps3QFCdEzPgkGbojkDRAeBj8MgUQEAVlA4IGgAAABQAgCdASoPABAAA4BaJYwCdAYrF8ALWVnzwsAA4BigOlruFh/qftbhFfNYMSWiWNQU3FoGjxN97b63SOmv+j9FEeXXqQV1W0i3+llOoTv8oIeWfuj6Ansz8odL/xPtlJmT4sMsqt8AAA==",
  "/vsl/marquee/10ft-studio.png": "data:image/webp;base64,UklGRoYAAABXRUJQVlA4WAoAAAAQAAAADwAACAAAQUxQSEQAAAABYFTbtpJ7keG3AH+EFYC5O1GIQFwC0MEhQUSQDVAUNo/glXRdhyTxUiKZOyuU0P4JF+u+LVmR5hI8TVDnVhhljvn9BlZQOCAcAAAAUAEAnQEqEAAJAAOAWiWkAAR0AAD9Mf//r4AAAA==",
  "/vsl/marquee/byeb.png": "data:image/webp;base64,UklGRoIAAABXRUJQVlA4WAoAAAAQAAAADwAACAAAQUxQSEAAAAABYFTbtpL7ZeqCw8graRkikIGkToOIUNi2DVIY7xF8IzmJH+SVj7NC3rcwx7hu+wh2D61wQ+3wdPN6TUEo/fgIVlA4IBwAAAAwAQCdASoQAAkAA4BaJaQAA3AA/TH//7DYAAAA",
  "/vsl/marquee/commission-club.png": "data:image/webp;base64,UklGRpoAAABXRUJQVlA4WAoAAAAQAAAADwAACAAAQUxQSD4AAAABf2AogNmkw1Ok9VpEhAC8NZjcA1FkK3moBaiAVWzg2MYglvBKPE9Choj+TwBJDUJxsw60d+4GxOcapDX4A1ZQOCA2AAAAsAEAnQEqEAAJAAOAWiWcAALaHL/aAAD+9wihGKntDae5b69fsKBp5IhEFBMJ4lv9/tcAAAAA",
  "/vsl/marquee/diamond-institute.png": "data:image/webp;base64,UklGRswAAABXRUJQVlA4WAoAAAAQAAAADwAACAAAQUxQSEMAAAABf6CgbRs21v2LYWAWEQEi0kxKpVuSB6NIsqt0/teXSEEGJyQgBw+IwgFyoiGi/2kTawIkxPU+BXF//wDnUSHWBJItAFZQOCBiAAAAUAIAnQEqEAAJAAOAWiWwAnQwSkiCR0bP/vAAAPQLjG0eb/bqMRFbSnClkXA/Lx0zCY2arGmmxzQwVjJZlTfPjxYqz5mj32uccJ+/X+I9oru2kd6o4PEMFYHy75kHsP6S0AA=",
  "/vsl/script/advisory-conversations.png": "data:image/webp;base64,UklGRiQAAABXRUJQVlA4IBgAAAAwAQCdASoQAAgAA4BaJaQAA3AA/vQRgAA=",
  "/vsl/script/compliance-rate.png": "data:image/webp;base64,UklGRigAAABXRUJQVlA4IBwAAAAwAQCdASoQAAYAA4BaJaQAA3AA/vPhDRgPAAAA",
  "/vsl/script/referral-funnel.png": "data:image/webp;base64,UklGRiwAAABXRUJQVlA4ICAAAAAwAQCdASoQAAUAA4BaJZwAA3AA/vN+79+2MjIHjgAAAA==",
  "/vsl/testimonials/cc-1.jpeg": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAACwAQCdASoQAAkAA4BaJQBOgCHeyyAAAP7xhOpVWxaHS8lIqv3nOcTjUrqptjQCEBr+YHAJNm5EaypxDNO60n70zSLQAA==",
  "/vsl/testimonials/cc-2.jpeg": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAACwAQCdASoQAAkAA4BaJQBOgCHeyyAAAP7xhOpVWxaHS8lIqv3nOcTjUrqptjQCEBr+YHAJNm5EaypxDNO60n70zSLQAA==",
  "/vsl/testimonials/cc-logo.png": "data:image/webp;base64,UklGRswAAABXRUJQVlA4WAoAAAAQAAAADwAABwAAQUxQSG0AAAANcFXbtqrs5+4C3+6RoAQ16EMQd3fXL3eIEBEKkzZg0nkL/hOZSU6zU+L28a6h9M1bzFGXFwRwYy5XgjkRAG5v3aolpie8rekZc7djKu9RDd+SWaw5OUqQB35jEN1F0Oy2xr3lEdiTS+C4nBEAAFZQOCA4AAAA0AEAnQEqEAAIAAOAWiWUAALc94B02AAA/vcQfZICL4J+99/TgG/yOL+sXn2ndSBO/TGO7bLyAAA=",
  "/vsl/testimonials/diamond-1.png": "data:image/webp;base64,UklGRioAAABXRUJQVlA4IB4AAAAwAQCdASoQAAoAA4BaJaQAA3AA/vQ/sCzeiugAAAA=",
  "/vsl/testimonials/diamond-2.jpeg": "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAAAQAgCdASoQAAsAA4BaJYgCdAEVLo9/FuUAAP7xhkNRMcDLplFIvGHl8lrKgdTznsKXmniJ3ANdpPh0fhML8/xJsfJB9ApjOkeYNPM3R4dCXmUiw6UcaeLe4LnGIEFjdgAAAA==",
  "/vsl/testimonials/diamond-3.jpeg": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAADwAQCdASoQAAsAA4BaJZgCdAEPS3sM3QAA/vSd9wQCPRsQZcvw4AgGq8p8SFD3yBrMOrNhSD96OsChkRHFIidXPlr6cRaM/4DyfLgsrpq9nEVcG58eNxj34gAAAA==",
  "/vsl/testimonials/diamond-logo.png": "data:image/webp;base64,UklGRhgBAABXRUJQVlA4WAoAAAAQAAAADwAABwAAQUxQSHMAAAANgGNb2/HqeWKbdVpWzqQykAzErDMFo7RxbX1vdecQEQkKAaHgv/VL/65XOqH8KgDF6Jd0n7TU/+mnJwqY9K/mnuiT6GUIACVzoYzMSqNujlRk+ECp7akdvlI5b75PI4BMeNF//iX/+PEHCJo9QlGBQggAAFZQOCB+AAAA8AEAnQEqEAAIAAOAWiWwAnQGKl3P+XKYAP146Hr8SvVn3uKpeYnl64TkGP7gbHqpyL5yeWiToXP4s1gDJoOPP1zz2ohqqris2fgtH9VIzWff/ApgvBfqynoLFO/NH9VWLa7yqMDlR7gleN07+k6GN1p3b7P9TduX6MyvAAAA",
  "/vsl/testimonials/galriv-1.png": "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAACwAQCdASoQAAkAA4BaJZwAAujcBDmAAP7qnkQku7cQlLALrxBwY1fpaEPMAFregAA=",
  "/vsl/testimonials/galriv-2.png": "data:image/webp;base64,UklGRjYAAABXRUJQVlA4ICoAAACwAQCdASoQAAUAA4BaJZwAAvc1IXHgAP7tZG2HaFSqTEp4N5D+M8i4AAA=",
  "/vsl/testimonials/galriv-logo.png": "data:image/webp;base64,UklGRoQAAABXRUJQVlA4WAoAAAAQAAAADwAAAwAAQUxQSC4AAAABYBvZVqpLBUSQkrnz3WPtvyRaiIgEIWjcO7/0tDCb1qUIIHTs7+RE9VnVLtEGVlA4IDAAAABwAQCdASoQAAQAA4BaJaACdAFAAAD+3A/5u0yF4ZQkGq1fgcErPnDc3sQTlNuVwAA=",
};
