// AUTO-GENERATED by scripts/generate-blur.mjs — do not edit by hand.
// Regenerate with `npm run blur` (runs automatically on `prebuild`).

export const BLUR_DATA: Record<string, string> = {
  "/home/logo.png": "data:image/webp;base64,UklGRi4BAABXRUJQVlA4WAoAAAAQAAAADgAADwAAQUxQSJ8AAAABgJtt27HnfvGbA7jz/0cz2NYETlrb7tK5tLVCSrdOm5T+/H0rRMQEQNPKoJeiLQxKtExY2QKBklDGGSofi+CzQ514k/0P11dWwOSN1E2cvgnCr9AFZqk8+BCEf+Hz7ksoBSNWWzC3c6YpZ0fYXItCnaNb+IsvLQMglHELRoRLwM2gyjEg1INBk2Ps3QFCdEzPgkGbojkDRAeBj8MgUQEAVlA4IGgAAABQAgCdASoPABAAA4BaJYwCdAYrF8ALWVnzwsAA4BigOlruFh/qftbhFfNYMSWiWNQU3FoGjxN97b63SOmv+j9FEeXXqQV1W0i3+llOoTv8oIeWfuj6Ansz8odL/xPtlJmT4sMsqt8AAA==",
};
