// AUTO-GENERATED by scripts/generate-blur.mjs — do not edit by hand.
// Regenerate with `npm run blur` (runs automatically on `prebuild`).

export const BLUR_DATA: Record<string, string> = {
  "/home/logo.png": "data:image/webp;base64,UklGRiYBAABXRUJQVlA4WAoAAAAQAAAADgAADwAAQUxQSJ4AAAABgJtt27HnevFbQevKXCFt0hkTWKVtJwM4nY0BssBfpbXZ/vYKETEBRBcmSbyS5iykjKXZ2EMRKaRSBmpfKsi2EDO1sPfOfWtBGuwFVeM3996AJ9CFMtXufwX8/sC/2xOoRCGTMst7lprKTgLruzlE1/QFPAUra4CQSpsZC1wiXIqomqFADYqYmsk3M0LEMTuHIraitQwRhyDNSIIiClZQOCBiAAAA0AEAnQEqDwAQAAOAWiWMAnR/AIJQlQAA4BigeltWOD05aq/kOmrij7x0kaJnu5ACdDcbLlKg3x63SWrP/+NbyL4xYi9r3bQC+tE8azpdgsYRDoCiPe2Fc/Qvt4Q8hCq7QAA=",
};
