// Build-time blur-placeholder generator.
//
// Walks public/ for raster images, downsamples each to a tiny (≤16px) WebP and
// emits a base64 data URL. The result is written to src/lib/blur-data.generated.ts
// as a Record keyed by the public path (e.g. "/testimonials/galriv-1.png").
//
// SmartImage looks the value up at render time and applies placeholder="blur",
// so an in-flight image never shows a blank box — it shows a styled blur of itself.
//
// Run automatically via the "prebuild" npm script, or manually with `npm run blur`.

import { readdir, mkdir, writeFile } from "node:fs/promises";
import { join, posix, relative, sep } from "node:path";
import { fileURLToPath } from "node:url";
import sharp from "sharp";

const ROOT = fileURLToPath(new URL("..", import.meta.url));
const PUBLIC_DIR = join(ROOT, "public");
const OUT_FILE = join(ROOT, "src", "lib", "blur-data.generated.ts");

const RASTER = new Set([".png", ".jpg", ".jpeg", ".webp", ".avif"]);

async function* walk(dir) {
  const entries = await readdir(dir, { withFileTypes: true });
  for (const entry of entries) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) {
      yield* walk(full);
    } else {
      const dot = entry.name.lastIndexOf(".");
      const ext = dot === -1 ? "" : entry.name.slice(dot).toLowerCase();
      if (RASTER.has(ext)) yield full;
    }
  }
}

async function blurDataURL(file) {
  const buf = await sharp(file)
    .resize(16, 16, { fit: "inside" })
    .webp({ quality: 40 })
    .toBuffer();
  return `data:image/webp;base64,${buf.toString("base64")}`;
}

async function main() {
  const map = {};
  for await (const file of walk(PUBLIC_DIR)) {
    // Public path: "/" + posix-relative path from public/
    const rel = relative(PUBLIC_DIR, file).split(sep).join(posix.sep);
    const publicPath = "/" + rel;
    try {
      map[publicPath] = await blurDataURL(file);
    } catch (err) {
      console.warn(`[blur] skipped ${publicPath}: ${err.message}`);
    }
  }

  const keys = Object.keys(map).sort();
  const body = keys.map((k) => `  ${JSON.stringify(k)}: ${JSON.stringify(map[k])},`).join("\n");

  const out =
    `// AUTO-GENERATED by scripts/generate-blur.mjs — do not edit by hand.\n` +
    `// Regenerate with \`npm run blur\` (runs automatically on \`prebuild\`).\n\n` +
    `export const BLUR_DATA: Record<string, string> = {\n${body}\n};\n`;

  await mkdir(join(ROOT, "src", "lib"), { recursive: true });
  await writeFile(OUT_FILE, out, "utf8");
  console.log(`[blur] wrote ${keys.length} placeholders → ${relative(ROOT, OUT_FILE)}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
